language: node_js
node_js:
  - node
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - yarn install
scripts:
  - cd blog
  - yarn docs:build
  - cd docs/.vuepress/dist
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push -f https://github.com/RatFrog/ratfrog.github.io.git master